apiVersion: apps/v1
kind: Deployment
metadata:
  name: download-service
  labels:
    app: download-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: download-service
  template:
    metadata:
      labels:
        app: download-service
    spec:
      containers:
        - name: download
          image: us.gcr.io/absolute-hub-262605/download-service:dev
          ports:
            - containerPort: 8080

