apiVersion: v1
kind: Service
metadata:
  name: download-service
  labels:
    app: download-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: download-service
