apiVersion: v1
kind: Service
metadata:
  name: transfer-web-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: transfer
    component: web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfer
      component: web
  template:
    metadata:
      labels:
        app: transfer
        component: web
    spec:
      containers:
        - name: transfer-web
          image: gcr.io/works-staging/transfer:1.0.0
          args: ["--provider=local", "--basedir=/data/files", "--meta-provider=redis"]
          env:
          - name: REDIS_ADDR
            value: "transfer-redis-service:6379"
          - name: HTTP_AUTH_USER
            valueFrom:
              secretKeyRef:
                name: transfer-secret
                key: auth_user
          - name: HTTP_AUTH_PASS
            valueFrom:
              secretKeyRef:
                name: transfer-secret
                key: auth_pass
          ports:
            - containerPort: 8080

